### ISSUE TITLE
Some more questions about the output

### ISSUE THREAD

**Issue by LucianZhan** [robertostling/efmaral#7]
"python3 align.py -i data.txt -v > test.moses --output-prob prob.txt"   
I run this, but only generates the file"prob1.txt" , there is nothing in test.moses( it should be the alignment result but the content in the file is empty).  And by the way, I also tried [eflomal](https://github.com/robertostling/eflomal) , it seems that it can only generate sentence_score, I don't know whether eflomal can also generate alignment probabilities like efmaral. Thank you for your kindness and patience.

**Comment by LucianZhan** [comment]
But if I run"python3 align.py -i data.txt -v > test.moses" (without the parameter '--output-prob') , the alignment result can be normally written to file "test.moses". If I add the the parameter '--output-prob' , "test.moses" is empty.

**Comment by robertostling** [comment]
You can easily change this behavior by editing the if statement in lines 74--78 of `align.py`:

    if discretize:
        ibm_print(aaa, args.reverse, sys.stdout.fileno())
    else:
        with open(args.output_prob, 'wb') as f:
            pickle.dump(aaa, f, -1)

Move the ibm_print() call outside the if statement, if you want both outputs at the same time.

As for eflomal, it would require a bit of work to output per-link probabilities, since the internal structure is different and the full probability matrices are not stored outside the inner loop. This (highly optimized C) code would have to be copied/modified to write out the full probabilities.
